### ISSUE TITLE
can you share train.py for oulu?

### ISSUE THREAD

**Issue by xiao-keeplearning** [VIS-VAR/LGSC-for-FAS#6]
I confuse about patched input, how to implement it?

**Comment by haochengV** [comment]
hi, xiao-keeplearning, we have submitted new code with patched input strategy, please infer #8

**Comment by CHNxindong** [comment]
> I confuse about patched input, how to implement it?

@xiao-keeplearning @haochengV hello, I am also training on oulu, can you share how to modify train.py? and do you know how to organise data format corresponding to oulu.py? thank you! thank you! thank you!!!
