### ISSUE TITLE
 patched input strategy

### ISSUE THREAD

**Issue by mydlgit** [VIS-VAR/LGSC-for-FAS#7]
In the paper, "we compare resizing the cropped faces to 224×224 with the bilinear interpolation
and patching 224×224 the patches from the face images, and patched input strategy achieves better ACER metric." I don't understand what's  'patched input strategy', can you explan that? thx!!!

**Comment by ZGSLZL** [comment]
Hi，mydlgit, this strategy is to crop the 224x224 patches directly from the original face images, which means that there is no resize operation

**Comment by VIS-VAR** [comment]
Hi mydlgit, we have submitted new code with patched input strategy, please infer https://github.com/VIS-VAR/LGSC-for-FAS/pull/8
