### ISSUE TITLE
About image preprocessing

### ISSUE THREAD

**Issue by ZhangYuanhan-AI** [VIS-VAR/LGSC-for-FAS#9]
Hi, Thanks for sharing this code. I have some question here.
In this progect, I can't find code about how to crop face image from original image. Have you already done this process locally？
Thanks for replying!

**Comment by haochengV** [comment]
Hi, David, in our experiments, we crop the human faces out of the images and feed them to the proposed framework. For datasets that offer no face location ground truth,  we use the Dlib toolbox as the face detector.

**Comment by ZhangYuanhan-AI** [comment]
Ok. Thansks!
